renewing of the PerfectHash values due to the new properties of diagonal and antidiagonal #1224
eclipse/birt pull request #1264
Opened 2023-04-13 19:25 UTC by speckyspooky

The added changes are the renew of the new designer properties of PerfectHash caused on #1224

2023-04-14 19:55 UTC, speckyspooky commented
I have added a README.md file. It is my first try with such kind of README-makefile.
Therefore I don't know exactly if I have reached all your requirements.

But the good thing is I installed cygwin and tested the steps with success(!)

2023-04-17 07:21 UTC, hvbtup commented
Thanks for the README.md file. I made some minor changes and added an example at the end.

Is the `BIRT Model Test (Engine).launch` file related to the change in any way?
If not, can you please remove it? It causes a conflict.

2023-04-17 07:23 UTC, hvbtup requested changes
I think the run configuration (which is probably not related to the changes) should be restored.

2023-04-18 07:28 UTC, hvbtup approved these changes

2023-04-18 18:02 UTC, merged