Fix core tests
eclipse/birt pull request #590
Opened 2021-03-05 19:43 UTC by Flugtiger

These commits try to fix the tests of the core plugin. One of the problems was the tests being dependent on the systems timezone / locale. My solution was to make the tests independent. Another solution would be to alter the system tz / locale in the maven build to the one the tests assume to be active (unclear what exactly it needs to be).

2021-03-06 08:45 UTC, ruspl-afed requested changes
Let's try to enable tests for this bundle to check the result of the fix

2021-03-06 08:45 UTC, ruspl-afed commented on core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/archive/AllArchiveTests.java
> +		// test.addTestSuite( TestBuffer.class );
We shouldn't have a code that just commented out. Let's either remove it or better convert it to the TestCase

2021-03-07 06:20 UTC, Flugtiger commented
Although tests have passed in this CI run, there's an occasional dead lock in org.eclipse.birt.core.archive.FolderArchiveTest which causes the build to hang indefinitely sometimes.

2021-03-07 07:23 UTC, ruspl-afed commented
@Flugtiger I suggest to merge this one and fight with `FolderArchiveTest` separately

2021-03-07 14:19 UTC, merged