Some reports created with birt 4.2.1 don't work with 4.9.0 #838
eclipse/birt pull request #845
Opened 2022-03-04 12:14 UTC by claesrosell

Added migration of old OdaDataSet that used translated strings
(Message.getString()), to the new property names introduced with commit
cac6e65a766ecbf1086728cebdbb5d54b4755728

I know that we are close to release, and introduce model migration for old issues may be a bad idea. - But here it is.

2022-03-04 12:20 UTC, wimjongman requested changes
Thank you, Claes. That looks great. We should maybe create a test case for that. I only found one minor issue.

2022-03-04 12:20 UTC, wimjongman commented on model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/OdaDataSetState.java
> +		doCompatibleConvertComputedColumnsConcatenateProperites(tmpElement);
Typo in the method name ...Properties

2022-03-04 12:46 UTC, claesrosell commented on model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/OdaDataSetState.java
> +		doCompatibleConvertComputedColumnsConcatenateProperites(tmpElement);
Fixed with latest commit.

2022-03-04 12:59 UTC, claesrosell commented
I am not good with unit tests, but I will try to add a test that uses the compareDesignModel() test util to determine if a migration is properly read/parsed.

2022-03-04 16:03 UTC, wimjongman commented
Ok, that would be great. Maybe @hvbargen can help you or design a proper test. It should not be hard to copy an existing test. Let me know if you need help.

2022-03-04 16:05 UTC, wimjongman approved these changes

2022-03-04 16:38 UTC, hvbtup commented
Sorry, I'm totally busy ATM, won't find the time to test this in the next few days. But skimming over the code changes, it looks good to me.

2022-03-04 21:12 UTC, claesrosell commented
Test added

2022-03-05 11:45 UTC, wimjongman approved these changes
Wonderful.

2022-03-05 11:46 UTC, wimjongman commented
Thanks, Claes. Please Squash and Merge.

2022-03-05 12:03 UTC, merged

2022-03-05 14:40 UTC, hvbargen commented
Thanks Claes. I'm looking forward to merge this into our product and test 
it with our patched BIRT and a complex report before April. This is very 
helpful.